import type { CategoryDefinition, CategoryId, ToolDefinition } from '@/types'

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: 'encoding',
    label: 'Encoding & Formatting',
    accentBg: 'bg-indigo-500',
    accentText: 'text-indigo-400',
    accentBorder: 'border-indigo-500',
    accentSubtle: 'bg-indigo-500/10',
    accentRing: 'ring-indigo-500/30',
  },
  {
    id: 'crypto',
    label: 'Crypto & Security',
    accentBg: 'bg-amber-500',
    accentText: 'text-amber-400',
    accentBorder: 'border-amber-500',
    accentSubtle: 'bg-amber-500/10',
    accentRing: 'ring-amber-500/30',
  },
  {
    id: 'dev',
    label: 'Developer Utilities',
    accentBg: 'bg-emerald-500',
    accentText: 'text-emerald-400',
    accentBorder: 'border-emerald-500',
    accentSubtle: 'bg-emerald-500/10',
    accentRing: 'ring-emerald-500/30',
  },
  {
    id: 'image',
    label: 'Image & Document',
    accentBg: 'bg-rose-500',
    accentText: 'text-rose-400',
    accentBorder: 'border-rose-500',
    accentSubtle: 'bg-rose-500/10',
    accentRing: 'ring-rose-500/30',
  },
  {
    id: 'office',
    label: 'Office Productivity',
    accentBg: 'bg-sky-500',
    accentText: 'text-sky-400',
    accentBorder: 'border-sky-500',
    accentSubtle: 'bg-sky-500/10',
    accentRing: 'ring-sky-500/30',
  },
  {
    id: 'visual',
    label: 'Visual & Design',
    accentBg: 'bg-violet-500',
    accentText: 'text-violet-400',
    accentBorder: 'border-violet-500',
    accentSubtle: 'bg-violet-500/10',
    accentRing: 'ring-violet-500/30',
  },
]

export const TOOLS: ToolDefinition[] = [
  // Encoding & Formatting
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    category: 'encoding',
    description: 'Format, validate, and explore JSON as a collapsible tree',
    icon: 'Braces',
    slug: 'json-formatter',
    keywords: ['json', 'format', 'validate', 'tree', 'pretty', 'lint', 'beautify'],
  },
  {
    id: 'json-converter',
    name: 'Data Converter',
    category: 'encoding',
    description: 'Convert between JSON, YAML, TOML, CSV, and XML',
    icon: 'ArrowLeftRight',
    slug: 'json-converter',
    keywords: ['json', 'yaml', 'toml', 'csv', 'xml', 'convert', 'transform'],
  },
  {
    id: 'base64',
    name: 'Base64',
    category: 'encoding',
    description: 'Encode and decode text, files, and images to/from Base64',
    icon: 'FileCode',
    slug: 'base64',
    keywords: ['base64', 'encode', 'decode', 'image', 'file', 'binary'],
  },
  {
    id: 'url-html-encode',
    name: 'URL & HTML Encode',
    category: 'encoding',
    description: 'URL encode/decode and HTML entity encode/decode',
    icon: 'Link',
    slug: 'url-html-encode',
    keywords: ['url', 'encode', 'decode', 'html', 'entity', 'percent', 'uri'],
  },
  {
    id: 'code-beautifier',
    name: 'Code Beautifier',
    category: 'encoding',
    description: 'Beautify and minify SQL, JavaScript, CSS, and HTML',
    icon: 'Code2',
    slug: 'code-beautifier',
    keywords: ['beautify', 'minify', 'format', 'sql', 'js', 'css', 'html', 'prettier'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    category: 'encoding',
    description: 'Convert text between camelCase, snake_case, kebab-case, and more',
    icon: 'Type',
    slug: 'case-converter',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'title', 'upper', 'lower'],
  },
  {
    id: 'line-tools',
    name: 'Line Tools',
    category: 'encoding',
    description: 'Sort, deduplicate, reverse, and trim lines of text',
    icon: 'List',
    slug: 'line-tools',
    keywords: ['sort', 'dedupe', 'deduplicate', 'reverse', 'trim', 'lines', 'unique'],
  },
  {
    id: 'string-tools',
    name: 'String Tools',
    category: 'encoding',
    description: 'Slugify, escape, and unescape strings (JSON, SQL, regex)',
    icon: 'Regex',
    slug: 'string-tools',
    keywords: ['slug', 'slugify', 'escape', 'unescape', 'json', 'sql', 'regex', 'string'],
  },
  // Crypto & Security
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    category: 'crypto',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, and HMAC hashes',
    icon: 'Hash',
    slug: 'hash-generator',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'hmac', 'checksum'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'crypto',
    description: 'Generate secure passwords with entropy and strength meter',
    icon: 'KeyRound',
    slug: 'password-generator',
    keywords: ['password', 'generate', 'random', 'secure', 'entropy', 'strength', 'keygen'],
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt',
    category: 'crypto',
    description: 'Hash and verify passwords with bcrypt',
    icon: 'ShieldCheck',
    slug: 'bcrypt',
    keywords: ['bcrypt', 'hash', 'password', 'verify', 'salt', 'rounds'],
  },
  {
    id: 'aes-encrypt',
    name: 'AES Encrypt/Decrypt',
    category: 'crypto',
    description: 'Encrypt and decrypt text with AES',
    icon: 'Lock',
    slug: 'aes-encrypt',
    keywords: ['aes', 'encrypt', 'decrypt', 'cipher', 'crypto', 'secret'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    category: 'crypto',
    description: 'Decode and inspect JWT tokens — header, payload, expiry',
    icon: 'Fingerprint',
    slug: 'jwt-decoder',
    keywords: ['jwt', 'token', 'decode', 'auth', 'bearer', 'payload', 'header'],
  },
  {
    id: 'uuid-ulid',
    name: 'UUID / ULID Generator',
    category: 'crypto',
    description: 'Generate UUIDs (v1, v4, v5) and ULIDs',
    icon: 'Shuffle',
    slug: 'uuid-ulid',
    keywords: ['uuid', 'ulid', 'guid', 'generate', 'unique', 'id'],
  },
  {
    id: 'totp',
    name: 'TOTP / 2FA Generator',
    category: 'crypto',
    description: 'Generate time-based one-time passwords for 2FA',
    icon: 'Timer',
    slug: 'totp',
    keywords: ['totp', '2fa', 'otp', 'authenticator', 'mfa', 'one-time', 'password'],
  },
  {
    id: 'qr-code',
    name: 'QR Code',
    category: 'crypto',
    description: 'Generate QR codes and read them via camera or image upload',
    icon: 'QrCode',
    slug: 'qr-code',
    keywords: ['qr', 'qrcode', 'scan', 'camera', 'generate', 'barcode'],
  },
  // Developer Utilities
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'dev',
    description: 'Test regular expressions with live highlighting and explanation',
    icon: 'Search',
    slug: 'regex-tester',
    keywords: ['regex', 'regexp', 'regular expression', 'test', 'match', 'pattern'],
  },
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    category: 'dev',
    description: 'Build and parse cron expressions with human-readable output',
    icon: 'CalendarClock',
    slug: 'cron-builder',
    keywords: ['cron', 'schedule', 'expression', 'build', 'parse', 'interval'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    category: 'dev',
    description: 'Convert Unix timestamps to human dates and back',
    icon: 'Clock',
    slug: 'timestamp-converter',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert'],
  },
  {
    id: 'base-converter',
    name: 'Number Base Converter',
    category: 'dev',
    description: 'Convert numbers between binary, octal, decimal, and hex',
    icon: 'Binary',
    slug: 'base-converter',
    keywords: ['binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'base', 'convert', 'number'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    category: 'dev',
    description: 'Convert colors between HEX, RGB, HSL with contrast checker',
    icon: 'Palette',
    slug: 'color-converter',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'palette', 'contrast', 'a11y', 'css'],
  },
  {
    id: 'fake-data-generator',
    name: 'Fake Data Generator',
    category: 'dev',
    description: 'Generate mock names, emails, addresses, and JSON rows',
    icon: 'UserCheck',
    slug: 'fake-data-generator',
    keywords: ['fake', 'mock', 'data', 'generate', 'name', 'email', 'address', 'json', 'faker'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    category: 'dev',
    description: 'Compare two text blocks or files side-by-side',
    icon: 'GitCompare',
    slug: 'text-diff',
    keywords: ['diff', 'compare', 'text', 'file', 'difference', 'patch'],
  },
  {
    id: 'markdown-converter',
    name: 'Markdown Converter',
    category: 'dev',
    description: 'Convert Markdown to HTML and back with live preview',
    icon: 'FileText',
    slug: 'markdown-converter',
    keywords: ['markdown', 'html', 'convert', 'preview', 'md', 'render'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    category: 'dev',
    description: 'Generate lorem ipsum placeholder text by words, sentences, or paragraphs',
    icon: 'AlignLeft',
    slug: 'lorem-ipsum',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate', 'dummy'],
  },
  {
    id: 'http-reference',
    name: 'HTTP Reference',
    category: 'dev',
    description: 'HTTP status codes and MIME types quick reference',
    icon: 'Globe',
    slug: 'http-reference',
    keywords: ['http', 'status', 'code', 'mime', 'type', 'reference', '404', '200', '500'],
  },
  // Image & Document
  {
    id: 'pdf-tools',
    name: 'PDF Tools',
    category: 'image',
    description: 'Merge, split, reorder, rotate, and compress PDF files',
    icon: 'FilePdf',
    slug: 'pdf-tools',
    keywords: ['pdf', 'merge', 'split', 'rotate', 'compress', 'reorder', 'combine'],
  },
  {
    id: 'pdf-image-converter',
    name: 'PDF ↔ Images',
    category: 'image',
    description: 'Convert PDF pages to images or combine images into a PDF',
    icon: 'FileImage',
    slug: 'pdf-image-converter',
    keywords: ['pdf', 'image', 'convert', 'png', 'jpg', 'pages', 'export'],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    category: 'image',
    description: 'Convert images between PNG, JPG, WebP, and AVIF formats',
    icon: 'ImageIcon',
    slug: 'image-converter',
    keywords: ['image', 'convert', 'png', 'jpg', 'jpeg', 'webp', 'avif', 'format'],
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    category: 'image',
    description: 'Resize, crop, and compress images in the browser',
    icon: 'Crop',
    slug: 'image-resize',
    keywords: ['image', 'resize', 'crop', 'compress', 'scale', 'width', 'height'],
  },
  {
    id: 'svg-tools',
    name: 'SVG Tools',
    category: 'image',
    description: 'Optimize SVGs and generate favicons from SVG or image',
    icon: 'VectorSquare',
    slug: 'svg-tools',
    keywords: ['svg', 'optimize', 'favicon', 'icon', 'minify', 'vector'],
  },
  {
    id: 'image-base64',
    name: 'Image → Base64',
    category: 'image',
    description: 'Convert images to Base64 data URIs for embedding in CSS or HTML',
    icon: 'Image',
    slug: 'image-base64',
    keywords: ['image', 'base64', 'data', 'uri', 'embed', 'css', 'html'],
  },
  // Office Productivity
  {
    id: 'pomodoro',
    name: 'Pomodoro',
    category: 'office',
    description: 'Pomodoro timer and stopwatch for focused work sessions',
    icon: 'TimerIcon',
    slug: 'pomodoro',
    keywords: ['pomodoro', 'timer', 'stopwatch', 'focus', 'break', 'productivity'],
  },
  {
    id: 'timezone-clock',
    name: 'Timezone Converter',
    category: 'office',
    description: 'Convert times across timezones and view a live world clock',
    icon: 'Globe2',
    slug: 'timezone-clock',
    keywords: ['timezone', 'time', 'world', 'clock', 'utc', 'convert', 'remote', 'team'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'office',
    description: 'Convert length, weight, temperature, and data sizes',
    icon: 'Ruler',
    slug: 'unit-converter',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'data', 'bytes', 'metric'],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    category: 'office',
    description: 'Calculate days between dates and add/subtract business days',
    icon: 'CalendarDays',
    slug: 'date-calculator',
    keywords: ['date', 'calculate', 'days', 'between', 'business', 'add', 'subtract', 'difference'],
  },
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'office',
    description: 'Scientific and percentage calculator',
    icon: 'Calculator',
    slug: 'calculator',
    keywords: ['calculator', 'math', 'scientific', 'percentage', 'compute', 'formula'],
  },
  {
    id: 'csv-editor',
    name: 'CSV Editor',
    category: 'office',
    description: 'View and edit CSV files as a lightweight spreadsheet',
    icon: 'Table',
    slug: 'csv-editor',
    keywords: ['csv', 'spreadsheet', 'table', 'edit', 'view', 'data'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'office',
    description: 'Count words, characters, sentences, and estimate reading time',
    icon: 'AlignJustify',
    slug: 'word-counter',
    keywords: ['word', 'character', 'count', 'reading', 'time', 'text', 'length'],
  },
  {
    id: 'scratchpad',
    name: 'Scratchpad',
    category: 'office',
    description: 'Local notes and quick to-do list, persisted in browser storage',
    icon: 'NotebookPen',
    slug: 'scratchpad',
    keywords: ['note', 'scratchpad', 'todo', 'list', 'text', 'local', 'scratch'],
  },
  {
    id: 'meeting-cost',
    name: 'Meeting Cost',
    category: 'office',
    description: 'Calculate the real cost of a meeting based on attendees and salaries',
    icon: 'DollarSign',
    slug: 'meeting-cost',
    keywords: ['meeting', 'cost', 'salary', 'time', 'money', 'attendees', 'expensive'],
  },
  {
    id: 'pastebin',
    name: 'Pastebin',
    category: 'office',
    description: 'Local pastebin — save and retrieve text snippets by name',
    icon: 'ClipboardList',
    slug: 'pastebin',
    keywords: ['paste', 'snippet', 'save', 'local', 'clipboard', 'text', 'store'],
  },
  // Visual & Design
  {
    id: 'css-generators',
    name: 'CSS Generators',
    category: 'visual',
    description: 'Generate CSS box-shadow and gradient values with live preview',
    icon: 'Wand2',
    slug: 'css-generators',
    keywords: ['css', 'box-shadow', 'gradient', 'generate', 'shadow', 'background'],
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    category: 'visual',
    description: 'Freeform drawing and diagramming canvas',
    icon: 'PenTool',
    slug: 'whiteboard',
    keywords: ['whiteboard', 'draw', 'diagram', 'canvas', 'sketch', 'freeform'],
  },
  {
    id: 'mermaid',
    name: 'Mermaid Diagrams',
    category: 'visual',
    description: 'Render Mermaid flowcharts and diagrams from text',
    icon: 'GitBranch',
    slug: 'mermaid',
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'graph', 'render'],
  },
  {
    id: 'image-annotator',
    name: 'Image Annotator',
    category: 'visual',
    description: 'Annotate and mark up screenshots and images',
    icon: 'MousePointer2',
    slug: 'image-annotator',
    keywords: ['annotate', 'markup', 'screenshot', 'image', 'arrow', 'highlight', 'draw'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    category: 'visual',
    description: 'Color wheel, palette generator, and harmony explorer',
    icon: 'CircleDot',
    slug: 'color-palette',
    keywords: ['color', 'palette', 'wheel', 'harmony', 'complementary', 'generate', 'hue'],
  },
]

export function getToolsByCategory(categoryId: CategoryId): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === categoryId)
}

export function getToolByRoute(category: string, tool: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.category === category && t.slug === tool)
}

export function getCategoryById(id: CategoryId): CategoryDefinition | undefined {
  return CATEGORIES.find((c) => c.id === id)
}
