import type { CategoryDefinition, CategoryId, ToolDefinition } from '@/types'

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: 'encoding',
    label: 'Encoding & Formatting',
    accentBg: 'bg-indigo-500',
    accentText: 'text-indigo-400',
    accentBorder: 'border-indigo-500',
    accentSubtle: 'bg-indigo-500/10',
    accentRing: 'ring-indigo-500/30',
  },
  {
    id: 'crypto',
    label: 'Crypto & Security',
    accentBg: 'bg-amber-500',
    accentText: 'text-amber-400',
    accentBorder: 'border-amber-500',
    accentSubtle: 'bg-amber-500/10',
    accentRing: 'ring-amber-500/30',
  },
  {
    id: 'dev',
    label: 'Developer Utilities',
    accentBg: 'bg-emerald-500',
    accentText: 'text-emerald-400',
    accentBorder: 'border-emerald-500',
    accentSubtle: 'bg-emerald-500/10',
    accentRing: 'ring-emerald-500/30',
  },
  {
    id: 'image',
    label: 'Image & Document',
    accentBg: 'bg-rose-500',
    accentText: 'text-rose-400',
    accentBorder: 'border-rose-500',
    accentSubtle: 'bg-rose-500/10',
    accentRing: 'ring-rose-500/30',
  },
  {
    id: 'office',
    label: 'Office Productivity',
    accentBg: 'bg-sky-500',
    accentText: 'text-sky-400',
    accentBorder: 'border-sky-500',
    accentSubtle: 'bg-sky-500/10',
    accentRing: 'ring-sky-500/30',
  },
  {
    id: 'visual',
    label: 'Visual & Design',
    accentBg: 'bg-violet-500',
    accentText: 'text-violet-400',
    accentBorder: 'border-violet-500',
    accentSubtle: 'bg-violet-500/10',
    accentRing: 'ring-violet-500/30',
  },
  {
    id: 'education',
    label: 'Education & Study',
    accentBg: 'bg-teal-500',
    accentText: 'text-teal-400',
    accentBorder: 'border-teal-500',
    accentSubtle: 'bg-teal-500/10',
    accentRing: 'ring-teal-500/30',
  },
]

export const TOOLS: ToolDefinition[] = [
  // Encoding & Formatting
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    category: 'encoding',
    description: 'Format, validate, and explore JSON as a collapsible tree',
    icon: 'Braces',
    slug: 'json-formatter',
    keywords: ['json', 'format', 'validate', 'tree', 'pretty', 'lint', 'beautify'],
  },
  {
    id: 'json-converter',
    name: 'Data Converter',
    category: 'encoding',
    description: 'Convert between JSON, YAML, TOML, CSV, and XML',
    icon: 'ArrowLeftRight',
    slug: 'json-converter',
    keywords: ['json', 'yaml', 'toml', 'csv', 'xml', 'convert', 'transform'],
  },
  {
    id: 'base64',
    name: 'Base64',
    category: 'encoding',
    description: 'Encode and decode text, files, and images to/from Base64',
    icon: 'FileCode',
    slug: 'base64',
    keywords: ['base64', 'encode', 'decode', 'image', 'file', 'binary'],
  },
  {
    id: 'url-html-encode',
    name: 'URL & HTML Encode',
    category: 'encoding',
    description: 'URL encode/decode and HTML entity encode/decode',
    icon: 'Link',
    slug: 'url-html-encode',
    keywords: ['url', 'encode', 'decode', 'html', 'entity', 'percent', 'uri'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    category: 'encoding',
    description: 'Format and minify SQL queries with keyword highlighting and indentation',
    icon: 'Database',
    slug: 'sql-formatter',
    keywords: ['sql', 'format', 'beautify', 'minify', 'query', 'database', 'indent', 'mysql', 'postgres'],
  },
  {
    id: 'schema-generator',
    name: 'Schema Generator',
    category: 'encoding',
    description: 'Generate TypeScript interfaces, Zod schemas, and JSON Schema from CSV or JSON',
    icon: 'FileCode2',
    slug: 'schema-generator',
    keywords: ['typescript', 'interface', 'zod', 'schema', 'json', 'csv', 'generate', 'types'],
  },
  {
    id: 'csv-merger',
    name: 'CSV / Excel Merger',
    category: 'encoding',
    description: 'Merge multiple CSV files with matching columns into one download',
    icon: 'TableProperties',
    slug: 'csv-merger',
    keywords: ['csv', 'merge', 'join', 'combine', 'rows', 'files', 'tabular'],
  },
  {
    id: 'code-beautifier',
    name: 'Code Beautifier',
    category: 'encoding',
    description: 'Beautify and minify SQL, JavaScript, CSS, and HTML',
    icon: 'Code2',
    slug: 'code-beautifier',
    keywords: ['beautify', 'minify', 'format', 'sql', 'js', 'css', 'html', 'prettier'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    category: 'encoding',
    description: 'Convert text between camelCase, snake_case, kebab-case, and more',
    icon: 'Type',
    slug: 'case-converter',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'title', 'upper', 'lower'],
  },
  {
    id: 'line-tools',
    name: 'Line Tools',
    category: 'encoding',
    description: 'Sort, deduplicate, reverse, and trim lines of text',
    icon: 'List',
    slug: 'line-tools',
    keywords: ['sort', 'dedupe', 'deduplicate', 'reverse', 'trim', 'lines', 'unique'],
  },
  {
    id: 'string-tools',
    name: 'String Tools',
    category: 'encoding',
    description: 'Slugify, escape, and unescape strings (JSON, SQL, regex)',
    icon: 'Regex',
    slug: 'string-tools',
    keywords: ['slug', 'slugify', 'escape', 'unescape', 'json', 'sql', 'regex', 'string'],
  },
  // Crypto & Security
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    category: 'crypto',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, and HMAC hashes',
    icon: 'Hash',
    slug: 'hash-generator',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'hmac', 'checksum'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'crypto',
    description: 'Generate secure passwords with entropy and strength meter',
    icon: 'KeyRound',
    slug: 'password-generator',
    keywords: ['password', 'generate', 'random', 'secure', 'entropy', 'strength', 'keygen'],
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt',
    category: 'crypto',
    description: 'Hash and verify passwords with bcrypt',
    icon: 'ShieldCheck',
    slug: 'bcrypt',
    keywords: ['bcrypt', 'hash', 'password', 'verify', 'salt', 'rounds'],
  },
  {
    id: 'aes-encrypt',
    name: 'AES Encrypt/Decrypt',
    category: 'crypto',
    description: 'Encrypt and decrypt text with AES',
    icon: 'Lock',
    slug: 'aes-encrypt',
    keywords: ['aes', 'encrypt', 'decrypt', 'cipher', 'crypto', 'secret'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    category: 'crypto',
    description: 'Decode and inspect JWT tokens : header, payload, expiry',
    icon: 'Fingerprint',
    slug: 'jwt-decoder',
    keywords: ['jwt', 'token', 'decode', 'auth', 'bearer', 'payload', 'header'],
  },
  {
    id: 'uuid-ulid',
    name: 'UUID / ULID Generator',
    category: 'crypto',
    description: 'Generate UUIDs (v1, v4, v5) and ULIDs',
    icon: 'Shuffle',
    slug: 'uuid-ulid',
    keywords: ['uuid', 'ulid', 'guid', 'generate', 'unique', 'id'],
  },
  {
    id: 'totp',
    name: 'TOTP / 2FA Generator',
    category: 'crypto',
    description: 'Generate time-based one-time passwords for 2FA for testing and app development purposes.',
    icon: 'Timer',
    slug: 'totp',
    keywords: ['totp', '2fa', 'otp', 'authenticator', 'mfa', 'one-time', 'password'],
  },
  {
    id: 'qr-code',
    name: 'QR Code',
    category: 'crypto',
    description: 'Generate QR codes and read them via camera or image upload',
    icon: 'QrCode',
    slug: 'qr-code',
    keywords: ['qr', 'qrcode', 'scan', 'camera', 'generate', 'barcode'],
  },
  // Developer Utilities
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'dev',
    description: 'Test regular expressions with live highlighting and explanation',
    icon: 'Search',
    slug: 'regex-tester',
    keywords: ['regex', 'regexp', 'regular expression', 'test', 'match', 'pattern'],
  },
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    category: 'dev',
    description: 'Build and parse cron expressions with human-readable output',
    icon: 'CalendarClock',
    slug: 'cron-builder',
    keywords: ['cron', 'schedule', 'expression', 'build', 'parse', 'interval'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    category: 'dev',
    description: 'Convert Unix timestamps to human dates and back',
    icon: 'Clock',
    slug: 'timestamp-converter',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert'],
  },
  {
    id: 'base-converter',
    name: 'Number Base Converter',
    category: 'dev',
    description: 'Convert numbers between binary, octal, decimal, and hex',
    icon: 'Binary',
    slug: 'base-converter',
    keywords: ['binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'base', 'convert', 'number'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    category: 'dev',
    description: 'Convert colors between HEX, RGB, HSL with contrast checker',
    icon: 'Palette',
    slug: 'color-converter',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'palette', 'contrast', 'a11y', 'css'],
  },
  {
    id: 'fake-data-generator',
    name: 'Fake Data Generator',
    category: 'dev',
    description: 'Generate mock names, emails, addresses, and JSON rows',
    icon: 'UserCheck',
    slug: 'fake-data-generator',
    keywords: ['fake', 'mock', 'data', 'generate', 'name', 'email', 'address', 'json', 'faker'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    category: 'dev',
    description: 'Compare two text blocks or files side-by-side',
    icon: 'GitCompare',
    slug: 'text-diff',
    keywords: ['diff', 'compare', 'text', 'file', 'difference', 'patch'],
  },
  {
    id: 'markdown-converter',
    name: 'Markdown ↔ HTML',
    category: 'dev',
    description: 'Convert Markdown to HTML and back with live preview',
    icon: 'FileText',
    slug: 'markdown-converter',
    keywords: ['markdown', 'html', 'convert', 'preview', 'md', 'render'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    category: 'dev',
    description: 'Generate lorem ipsum placeholder text by words, sentences, or paragraphs',
    icon: 'AlignLeft',
    slug: 'lorem-ipsum',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate', 'dummy'],
  },
  {
    id: 'http-reference',
    name: 'HTTP Reference',
    category: 'dev',
    description: 'HTTP status codes and MIME types quick reference',
    icon: 'Globe',
    slug: 'http-reference',
    keywords: ['http', 'status', 'code', 'mime', 'type', 'reference', '404', '200', '500'],
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    category: 'dev',
    description: 'Offline markdown editor : open, edit, and save .md files from your local disk',
    icon: 'FileEdit',
    slug: 'markdown-editor',
    keywords: ['markdown', 'editor', 'md', 'write', 'local', 'file', 'offline', 'preview', 'save'],
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code',
    category: 'dev',
    description: 'Convert cURL commands to JavaScript fetch, Axios, Python, Go, and PHP code',
    icon: 'Terminal',
    slug: 'curl-to-code',
    keywords: ['curl', 'fetch', 'axios', 'python', 'requests', 'go', 'php', 'convert', 'snippet', 'http'],
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    category: 'dev',
    description: 'Test HTTP endpoints and webhooks locally — method, headers, body, response viewer',
    icon: 'Webhook',
    slug: 'api-tester',
    keywords: ['api', 'http', 'request', 'test', 'webhook', 'localhost', 'postman', 'rest', 'get', 'post', 'headers'],
  },
  {
    id: 'protobuf-inspector',
    name: 'Protobuf & Hex Inspector',
    category: 'dev',
    description: 'Decode protobuf payloads from hex, Base64, or a file — with a synced hex dump and optional .proto schema',
    icon: 'FileDigit',
    slug: 'protobuf-inspector',
    keywords: ['protobuf', 'proto', 'grpc', 'hex', 'decode', 'wire format', 'varint', 'binary', 'dump', 'byte'],
  },
  {
    id: 'ktp-mock-generator',
    name: 'KTP Mock Generator',
    category: 'dev',
    description: 'Generate fake Indonesian KTP data with structurally valid NIKs for QA and staging tests',
    icon: 'IdCard',
    slug: 'ktp-mock-generator',
    keywords: ['ktp', 'nik', 'mock', 'fake', 'data', 'indonesia', 'identitas', 'qa', 'staging', 'dukcapil', 'kependudukan'],
  },
  // Image & Document
  {
    id: 'pdf-tools',
    name: 'PDF Tools',
    category: 'image',
    description: 'Merge, split, reorder, rotate, and compress PDF files',
    icon: 'FilePdf',
    slug: 'pdf-tools',
    keywords: ['pdf', 'merge', 'split', 'rotate', 'compress', 'reorder', 'combine'],
  },
  {
    id: 'pdf-image-converter',
    name: 'PDF ↔ Images',
    category: 'image',
    description: 'Convert PDF pages to images or combine images into a PDF',
    icon: 'FileImage',
    slug: 'pdf-image-converter',
    keywords: ['pdf', 'image', 'convert', 'png', 'jpg', 'pages', 'export'],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    category: 'image',
    description: 'Convert images between PNG, JPG, WebP, and AVIF formats',
    icon: 'ImageIcon',
    slug: 'image-converter',
    keywords: ['image', 'convert', 'png', 'jpg', 'jpeg', 'webp', 'avif', 'format'],
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    category: 'image',
    description: 'Resize, crop, and compress images in the browser',
    icon: 'Crop',
    slug: 'image-resize',
    keywords: ['image', 'resize', 'crop', 'compress', 'scale', 'width', 'height'],
  },
  {
    id: 'svg-tools',
    name: 'SVG Tools',
    category: 'image',
    description: 'Optimize SVGs and generate favicons from SVG or image',
    icon: 'VectorSquare',
    slug: 'svg-tools',
    keywords: ['svg', 'optimize', 'favicon', 'icon', 'minify', 'vector'],
  },
  {
    id: 'image-base64',
    name: 'Image → Base64',
    category: 'image',
    description: 'Convert images to Base64 data URIs for embedding in CSS or HTML',
    icon: 'Image',
    slug: 'image-base64',
    keywords: ['image', 'base64', 'data', 'uri', 'embed', 'css', 'html'],
  },
  {
    id: 'exif-remover',
    name: 'EXIF Remover',
    category: 'image',
    description: 'Strip EXIF metadata (GPS, camera, dates) from JPEG, PNG, and HEIC/HEVC images before sharing',
    icon: 'ShieldOff',
    slug: 'exif-remover',
    keywords: ['exif', 'metadata', 'strip', 'remove', 'gps', 'location', 'privacy', 'image', 'photo', 'jpeg', 'heic', 'heif', 'hevc', 'iphone'],
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter & Merger',
    category: 'image',
    description: 'Select pages to extract or merge multiple PDFs into one file — fully offline',
    icon: 'FilePdf2',
    slug: 'pdf-splitter',
    keywords: ['pdf', 'split', 'merge', 'extract', 'pages', 'combine', 'offline', 'document'],
  },
  // Office Productivity
  {
    id: 'pomodoro',
    name: 'Pomodoro',
    category: 'office',
    description: 'Pomodoro timer and stopwatch for focused work sessions',
    icon: 'TimerIcon',
    slug: 'pomodoro',
    keywords: ['pomodoro', 'timer', 'stopwatch', 'focus', 'break', 'productivity'],
  },
  {
    id: 'timezone-clock',
    name: 'Timezone Converter',
    category: 'office',
    description: 'Convert times across timezones and view a live world clock',
    icon: 'Globe2',
    slug: 'timezone-clock',
    keywords: ['timezone', 'time', 'world', 'clock', 'utc', 'convert', 'remote', 'team'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'office',
    description: 'Convert length, weight, temperature, and data sizes',
    icon: 'Ruler',
    slug: 'unit-converter',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'data', 'bytes', 'metric'],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    category: 'office',
    description: 'Calculate days between dates and add/subtract business days',
    icon: 'CalendarDays',
    slug: 'date-calculator',
    keywords: ['date', 'calculate', 'days', 'between', 'business', 'add', 'subtract', 'difference'],
  },
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'office',
    description: 'Scientific and percentage calculator',
    icon: 'Calculator',
    slug: 'calculator',
    keywords: ['calculator', 'math', 'scientific', 'percentage', 'compute', 'formula'],
  },
  {
    id: 'csv-editor',
    name: 'CSV Editor',
    category: 'office',
    description: 'View and edit CSV files as a lightweight spreadsheet',
    icon: 'Table',
    slug: 'csv-editor',
    keywords: ['csv', 'spreadsheet', 'table', 'edit', 'view', 'data'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'office',
    description: 'Count words, characters, sentences, and estimate reading time',
    icon: 'AlignJustify',
    slug: 'word-counter',
    keywords: ['word', 'character', 'count', 'reading', 'time', 'text', 'length'],
  },
  {
    id: 'scratchpad',
    name: 'Scratchpad',
    category: 'office',
    description: 'Local notes and quick to-do list, persisted in browser storage',
    icon: 'NotebookPen',
    slug: 'scratchpad',
    keywords: ['note', 'scratchpad', 'todo', 'list', 'text', 'local', 'scratch'],
  },
  {
    id: 'meeting-cost',
    name: 'Meeting Cost',
    category: 'office',
    description: 'Calculate the real cost of a meeting based on attendees and salaries',
    icon: 'DollarSign',
    slug: 'meeting-cost',
    keywords: ['meeting', 'cost', 'salary', 'time', 'money', 'attendees', 'expensive'],
  },
  {
    id: 'pastebin',
    name: 'Pastebin',
    category: 'office',
    description: 'Local pastebin : save and retrieve text snippets by name',
    icon: 'ClipboardList',
    slug: 'pastebin',
    keywords: ['paste', 'snippet', 'save', 'local', 'clipboard', 'text', 'store'],
  },
  {
    id: 'task-tracker',
    name: 'Task Tracker',
    category: 'office',
    description: 'Offline Kanban board : columns, cards, labels, checklists and due dates',
    icon: 'KanbanSquare',
    slug: 'task-tracker',
    keywords: ['kanban', 'trello', 'task', 'board', 'project', 'card', 'todo', 'offline', 'column'],
  },
  {
    id: 'session-timer',
    name: 'Session Timer',
    category: 'office',
    description: 'Multi-timer stopwatch for tracking billable hours across projects',
    icon: 'Timer',
    slug: 'session-timer',
    keywords: ['timer', 'stopwatch', 'session', 'billable', 'hours', 'track', 'project', 'time'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Cleaner',
    category: 'office',
    description: 'Fix broken text from PDFs and emails: title case, clean spacing, remove junk characters',
    icon: 'Eraser',
    slug: 'text-cleaner',
    keywords: ['text', 'clean', 'case', 'title', 'sentence', 'spacing', 'format', 'paste', 'pdf', 'email'],
  },
  {
    id: 'speech-timer',
    name: 'Speech Timer',
    category: 'office',
    description: 'Estimate speaking time for scripts and presentations by word count and pace',
    icon: 'Mic',
    slug: 'speech-timer',
    keywords: ['speech', 'speaking', 'time', 'estimate', 'words', 'presentation', 'script', 'minutes', 'pace'],
  },
  {
    id: 'hours-calculator',
    name: 'Working Hours Calculator',
    category: 'office',
    description: 'Calculate total hours worked from start/end times with break deductions and overtime',
    icon: 'Clock4',
    slug: 'hours-calculator',
    keywords: ['hours', 'working', 'time', 'calculate', 'overtime', 'break', 'timesheet', 'payroll', 'freelance'],
  },
  {
    id: 'income-tax-calculator',
    name: 'Income Tax Calculator (PPh 21)',
    category: 'office',
    description: 'Calculate Indonesian income tax, BPJS Kesehatan, and BPJS Ketenagakerjaan from gross salary or take-home pay',
    icon: 'Landmark',
    slug: 'income-tax-calculator',
    keywords: ['pph21', 'pph 21', 'pajak', 'penghasilan', 'income tax', 'tax', 'bpjs', 'ketenagakerjaan', 'kesehatan', 'gaji', 'salary', 'take home pay', 'thp', 'ter', 'payroll', 'indonesia'],
  },
  {
    id: 'ppn-calculator',
    name: 'VAT Calculator (PPN)',
    category: 'office',
    description: 'Calculate Indonesian VAT (PPN) on purchases, both inclusive and exclusive of tax',
    icon: 'Receipt',
    slug: 'ppn-calculator',
    keywords: ['ppn', 'vat', 'pajak', 'pertambahan', 'nilai', 'tax', 'consumption', 'purchase', 'barang', 'jasa', 'mewah', 'luxury', 'indonesia'],
  },
  // Visual & Design
  {
    id: 'css-generators',
    name: 'CSS Generators',
    category: 'visual',
    description: 'Generate CSS box-shadow and gradient values with live preview',
    icon: 'Wand2',
    slug: 'css-generators',
    keywords: ['css', 'box-shadow', 'gradient', 'generate', 'shadow', 'background'],
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    category: 'visual',
    description: 'Freeform drawing and diagramming canvas',
    icon: 'PenTool',
    slug: 'whiteboard',
    keywords: ['whiteboard', 'draw', 'diagram', 'canvas', 'sketch', 'freeform'],
  },
  {
    id: 'mermaid',
    name: 'Mermaid Diagrams',
    category: 'visual',
    description: 'Render Mermaid flowcharts and diagrams from text',
    icon: 'GitBranch',
    slug: 'mermaid',
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'graph', 'render'],
  },
  {
    id: 'image-annotator',
    name: 'Image Annotator',
    category: 'visual',
    description: 'Annotate and mark up screenshots and images',
    icon: 'MousePointer2',
    slug: 'image-annotator',
    keywords: ['annotate', 'markup', 'screenshot', 'image', 'arrow', 'highlight', 'draw'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    category: 'visual',
    description: 'Color wheel, palette generator, and harmony explorer',
    icon: 'CircleDot',
    slug: 'color-palette',
    keywords: ['color', 'palette', 'wheel', 'harmony', 'complementary', 'generate', 'hue'],
  },
  // Education & Study
  {
    id: 'quadratic-solver',
    name: 'Quadratic Solver',
    category: 'education',
    description: 'Solve ax² + bx + c = 0 with step-by-step working',
    icon: 'Superscript',
    slug: 'quadratic-solver',
    keywords: ['quadratic', 'persamaan', 'kuadrat', 'discriminant', 'roots', 'akar', 'math', 'matematika'],
  },
  {
    id: 'matrix-calculator',
    name: 'Matrix Calculator',
    category: 'education',
    description: 'Add, multiply, determinant, inverse, and transpose matrices',
    icon: 'Grid2x2',
    slug: 'matrix-calculator',
    keywords: ['matrix', 'matriks', 'determinant', 'inverse', 'transpose', 'multiply', 'linear algebra'],
  },
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    category: 'education',
    description: 'Full scientific calculator with trig, log, and constants',
    icon: 'CalculatorIcon',
    slug: 'scientific-calculator',
    keywords: ['scientific', 'kalkulator', 'sin', 'cos', 'tan', 'log', 'sqrt', 'trigonometry', 'trigonometri'],
  },
  {
    id: 'statistics-calculator',
    name: 'Statistics Calculator',
    category: 'education',
    description: 'Mean, median, mode, variance, standard deviation and more',
    icon: 'BarChart2',
    slug: 'statistics-calculator',
    keywords: ['statistics', 'statistika', 'mean', 'median', 'mode', 'modus', 'variance', 'std dev', 'rata-rata'],
  },
  {
    id: 'molar-mass',
    name: 'Molar Mass Calculator',
    category: 'education',
    description: 'Calculate molar mass from a chemical formula like H₂SO₄',
    icon: 'FlaskConical',
    slug: 'molar-mass',
    keywords: ['molar', 'mass', 'kimia', 'chemistry', 'formula', 'atom', 'molekul', 'periodic table'],
  },
  {
    id: 'physics-solver',
    name: 'Physics Formula Solver',
    category: 'education',
    description: 'Solve physics formulas for GLBB, momentum, Ohm\'s law, and more',
    icon: 'Atom',
    slug: 'physics-solver',
    keywords: ['physics', 'fisika', 'GLBB', 'momentum', 'kinematika', 'dinamika', 'ohm', 'formula', 'rumus'],
  },
  {
    id: 'citation-generator',
    name: 'Citation Generator',
    category: 'education',
    description: 'Generate APA, MLA, Chicago citations for books, articles, websites',
    icon: 'BookMarked',
    slug: 'citation-generator',
    keywords: ['citation', 'referensi', 'daftar pustaka', 'APA', 'MLA', 'Chicago', 'bibliography', 'skripsi'],
  },
  {
    id: 'gpa-calculator',
    name: 'GPA Calculator',
    category: 'education',
    description: 'Calculate GPA / IPK using the Indonesian SKS credit system',
    icon: 'GraduationCap',
    slug: 'gpa-calculator',
    keywords: ['IPK', 'GPA', 'SKS', 'nilai', 'grade', 'semester', 'kuliah', 'universitas', 'indeks prestasi'],
  },
]

export function getToolsByCategory(categoryId: CategoryId): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === categoryId)
}

export function getToolByRoute(category: string, tool: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.category === category && t.slug === tool)
}

export function getCategoryById(id: CategoryId): CategoryDefinition | undefined {
  return CATEGORIES.find((c) => c.id === id)
}
